services:
  - type: web
    name: Przychodnia_render
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_USER
        value: SBD17
      - key: DB_PASS
        value: haslo2025
      - key: DB_URL
        value: jdbc:oracle:thin:@155.158.112.45:1521:oltpstud
      - key: PORT
        value: 8080
